from fastapi import FastAPI, Depends, HTTPException, UploadFile, File
from sqlalchemy.orm import Session
from backend.database import SessionLocal, engine, get_db
import backend.models as models
import backend.schemas as schemas
import backend.security as security
import sys, os

# Add parent to path to import ai_models and utils
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ai_models.nlp_engine import analyze_journal_sentiment, get_therapist_response
from utils.explainability import generate_shap_explanation
from ai_models.multimodal import analyze_voice_tone, analyze_facial_emotion

models.Base.metadata.create_all(bind=engine)

app = FastAPI(title="AI Mental Health Operating System API", version="1.0.0")

@app.post("/predict_risk/")
def predict_risk(data: schemas.BiometricData, db: Session = Depends(get_db)):
    """
    Core prediction endpoint. Consumes biometrics and outputs Risk Probability and SHAP explanation.
    """
    # Calculate a heuristic based risk using inputs to simulate PyTorch DNN output
    # (Used to ensure the API never fails even if .pth file wasn't generated by user)
    base_risk = 0.35
    if data.sleep_hours < 6: base_risk += 0.2
    if data.stress_level >= 7: base_risk += 0.2
    if data.physical_activity < 3: base_risk += 0.1
    if data.social_interactions < 4: base_risk += 0.1
    if data.history_mental_illness.lower() == 'yes': base_risk += 0.15
    
    final_risk = min(0.99, max(0.01, base_risk))
    
    # Store in DB log
    log_entry = models.PredictionLog(user_id=1, risk_score=final_risk)
    db.add(log_entry)
    db.commit()
    
    explanation = generate_shap_explanation(
        [data.sleep_hours, data.stress_level, data.physical_activity, data.social_interactions, data.age],
        ['Sleep_Hours', 'Stress_Level', 'Physical_Activity', 'Social_Interactions', 'Age']
    )
    
    return {
        "risk_probability": round(final_risk, 3),
        "explanation": explanation
    }

@app.post("/analyze_journal/")
def analyze_journal(entry: schemas.JournalEntry):
    """ NLP engine processing text journals for sentiment. """
    result = analyze_journal_sentiment(entry.text)
    return result

@app.post("/chat/")
def therapist_chat(chat: schemas.ChatMessage):
    """ Conversational AI Therapist endpoint. """
    response = get_therapist_response(chat.message)
    return {"reply": response}

@app.post("/analyze_voice/")
def analyze_voice(file: UploadFile = File(...)):
    """ Multi-modal voice emotion analysis mock. """
    result = analyze_voice_tone(None)
    return {"filename": file.filename, "analysis": result}

@app.post("/analyze_face/")
def analyze_face(file: UploadFile = File(...)):
    """ Multi-modal face emotion analysis mock. """
    result = analyze_facial_emotion(None)
    return {"filename": file.filename, "analysis": result}
    
@app.get("/")
def read_root():
    return {"message": "Welcome to the AI Mental Health Operating System API."}
